### ISSUE TITLE
Lack of detection of sharedconfig.vdf

### ISSUE THREAD

**Issue by dreamer** [CorruptComputer/ProtonDB-to-Steam-Library#1]
Editing a script is not really user-friendly solution... at the very least script should provide autodetection with ability to pass user-selected file through command line parameter.

Common locations for Steam userdata in order as they should be searched:

    data_home = os.environ.get('XDG_DATA_HOME') or os.path.expanduser('~/.local/share')
    path_1 = os.path.join(data_home, 'Steam/userdata')
    path_2 = os.path.expanduser('~/.steam/root/userdata')
    path_3 = os.path.expanduser('~/.steam/steam/userdata')

Script should also account for the possibility of many users using the same machine (several subdirectories in useradata dir) and REFUSE to modify any user files without explicit instruction from user (so e.g. default to only listing existing tags).

**Comment by CorruptComputer** [comment]
I agree that the lack of detection is not very user friendly. This was definitely something I was planning on adding in the near future. The main problem is the selection of the userID, as this does not directly translate to SteamID, so I would need a way to lookup a Username to display alongside it.

**Comment by CorruptComputer** [comment]
I added path detection in ad6647c0c5d1f151e864f6ff320db14b210bac59 this should help with ease of use.

**Comment by CorruptComputer** [comment]
I think all points here may have been fixed? It now asks you at the end if you would like to save.
