### ISSUE TITLE
Tags not showing

### ISSUE THREAD

**Issue by ErikSteNL** [CorruptComputer/ProtonDB-to-Steam-Library#10]
Hello,

I tried launching the tool with:
`python3 ProtonDB-to-Steam-Library.py -s ~/.steam/root/userdata/{{userId}}/config/localconfig.vdf`
`python3 ProtonDB-to-Steam-Library.py -s ~/.steam/steam/userdata/{{userId}}/config/localconfig.vdf`
These commands find my games and find a rating but they both do not update the steam tags.

When I try:
`python3 ProtonDB-to-Steam-Library.py`
It gives me an error message:
Steam found at: /home/erik/.steam/steam/userdata
Found user 0: {{userId}}   {{userName}}
Only one user found.
Selected: /home/erik/.steam/steam/userdata/{{userId}}/7/remote/sharedconfig.vdf
Traceback (most recent call last):
  File "ProtonDB-to-Steam-Library.py", line 212, in <module>
    main(sys.argv[1:])
  File "ProtonDB-to-Steam-Library.py", line 147, in main
    for app_id in sharedconfig[configstore]["Software"]["Valve"]["Steam"]["Apps"]:
KeyError: 'Apps'

My sharedConfig.vdf in /home/erik/.steam/steam/userdata/{{userId}}/7 looks like this:

```
"UserRoamingConfigStore"
{
	"Software"
	{
		"Valve"
		{
			"Steam"
			{
				"SurveyDate"		"2019-06-08"
				"SurveyDateVersion"		"-3209234459468703784"
				"SteamDefaultDialog"		"#app_games"
				"StartMenuShortcutCheck"		"1"
				"DesktopShortcutCheck"		"0"
				"FriendsUI"
				{
					"FriendsUIJSON"		"{\"bNotifications_ShowIngame\":true,\"bNotifications_ShowOnline\":false,\"bNotifications_ShowMessage\":true,\"bNotifications_EventsAndAnnouncements\":true,\"bSounds_PlayIngame\":false,\"bSounds_PlayOnline\":false,\"bSounds_PlayMessage\":true,\"bSounds_EventsAndAnnouncements\":false,\"bAlwaysNewChatWindow\":false,\"bForceAlphabeticFriendSorting\":false,\"nChatFlashMode\":0,\"bRememberOpenChats\":true,\"bCompactQuickAccess\":false,\"bCompactFriendsList\":false,\"bNotifications_ShowChatRoomNotification\":true,\"bSounds_PlayChatRoomNotification\":true,\"bHideOfflineFriendsInTagGroups\":false,\"bHideCategorizedFriends\":false,\"bCategorizeInGameFriendsByGame\":true,\"nChatFontSize\":2,\"b24HourClock\":false,\"bDoNotDisturbMode\":false,\"bDisableEmbedInlining\":false,\"bSignIntoFriends\":false,\"bDisableSpellcheck\":false,\"featuresEnabled\":{\"DoNotDisturb\":1,\"LoaderWindowSynchronization\":1,\"NonFriendMessageHandling\":1,\"NewVoiceHotKeyState\":1,\"PersonaNotifications\":1}}"
				}
				"Tools"
				{
					"1054830"
					{
						"Registered"		"1"
					}
				}
				"SSAVersion"		"3"
			}
		}
	}
	"controller_config"
	{
		"512900"
		{
			"usetime"		"153.28009033203125"
		}
		"4760"
		{
			"usetime"		"561.8671875"
		}
	}
}
```

Any help would be appreciated.

**Comment by subwolf** [comment]
This requires you to follow the troubleshooting tip about not having games show up in your library.

**Comment by ErikSteNL** [comment]
Nice, it totally works now, sorry for the inconvenience!
Just by adding tags to all of them beforehand.
