### ISSUE TITLE
sharedconfig.vdf detection fail if multiple accounts have been logged in.

### ISSUE THREAD

**Issue by aTosser** [CorruptComputer/ProtonDB-to-Steam-Library#12]
If more than one steam account has logged in to the client there are multiple directories .../Steam/usesrdata/ and the script gets unhappy.

**Comment by CorruptComputer** [comment]
I thought I had taken care of that. Could you post the Script's output for you? Also I'm curious could you tell me if the first line in your .../Steam/userdata/[id]/config/localconfig.vdf is UserLocalConfigStore? This is what it uses to detect the username from that Steam ID.

I would ask for the file, but it contains quite a bit of personal information attached to your Steam account.

**Comment by CorruptComputer** [comment]
Could you try the version which I just uploaded and see if that fixed your issue? (90dd1a45907acb261a72580ab06b5e1b71b348fc)

**Comment by CorruptComputer** [comment]
I believe this has been fixed. If not, please re-open this issue!
