### ISSUE TITLE
Most games falling in to "Uncategorized"

### ISSUE THREAD

**Issue by FruityWelsh** [CorruptComputer/ProtonDB-to-Steam-Library#13]
Most of my games are falling into "Uncategorized" even native games. I checked with the ProtonDB website, and most of them are on ranked

**Comment by CorruptComputer** [comment]
This is actually due to issue in Steam, could you try this workaround for me? https://github.com/CorruptComputer/ProtonDB-to-Steam-Library#troubleshooting

**Comment by FruityWelsh** [comment]
Done, sorry about that. 
Works now.

**Comment by FruityWelsh** [comment]
Done, sorry about that. 
Works now.
