### ISSUE TITLE
App app Issue as well as a crash and key error 2183152720314 .. ? 

### ISSUE THREAD

**Issue by QuakeSinatra** [CorruptComputer/ProtonDB-to-Steam-Library#14]
I manually had to change the app to App in the sharedconfig file it now runs up to a point and gives me :  (error below) the key error doesnt seem to match to anything in the sharedconfig nor any game id .. not sure what to try next..

 `Traceback (most recent call last):
  File "ProtonDB-to-Steam-Library.py", line 160, in main
    tags = sharedconfig[configstore]["Software"]["Valve"]["Steam"]["Apps"][str(app_id)]["tags"].copy()
KeyError: '2183152720314'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ProtonDB-to-Steam-Library.py", line 212, in <module>
    main(sys.argv[1:])
  File "ProtonDB-to-Steam-Library.py", line 175, in main
    sharedconfig[configstore]["Software"]["Valve"]["Steam"]["Apps"][str(app_id)]["tags"] = vdf.VDFDict()
KeyError: '2183152720314'
`

**Comment by subwolf** [comment]
All I can find so far relates to this document - https://stackoverflow.com/questions/41258358/column-string-access-for-date-using-day

Sounds like the data isn't there. Have you tried the troubleshooting trip on the home page to update your game list?

**Comment by QuakeSinatra** [comment]
Yes did the troubleshooting. And i have a feeling it has to do with a game that i added to my library that it doesn't let me delete.. I think Black Mesa (before it actually had a working Linux version) I added a link to it and now that i have the actual Linux version ..went to remove the old one and cannot.. so maybe that's the non data one that is causing it

**Comment by CorruptComputer** [comment]
Could you upload your sharedconfig.vdf for me to take a look at it?

**Comment by QuakeSinatra** [comment]
Sure can .. do you want the content of the file .. pasted here or pastebin .. or full file via Dropbox or some other means ?? 
.. Thanks Sub (forgot to mention it earlier) and Thanks Corrupt  .

**Comment by CorruptComputer** [comment]
If you drag the file to GitHub you can upload it directly to here. But if you want to use pastebin that is fine too.

**Comment by QuakeSinatra** [comment]
Hope this works :) and hope that i sheds some light on the problem. The Tool seems REALLY cool!!

[sharedconfig.vdf.zip](https://github.com/CorruptComputer/ProtonDB-to-Steam-Library/files/3272726/sharedconfig.vdf.zip)

**Comment by QuakeSinatra** [comment]
oh and it isnt an actual zip file just .zip added so github recognized the file type

**Comment by CorruptComputer** [comment]
Could you try the version which I just uploaded and see if that fixed your issue? (90dd1a45907acb261a72580ab06b5e1b71b348fc)

**Comment by QuakeSinatra** [comment]
CC, i had the app that needed to be changed to App and the same crash with the same error on the new version 90dd1a459...

**Comment by CorruptComputer** [comment]
Yeah, I was hoping that this check would help with this issue as well: https://github.com/CorruptComputer/ProtonDB-to-Steam-Library/blob/master/ProtonDB-to-Steam-Library.py#L194

**Comment by CorruptComputer** [comment]
Also the app vs App error should have been fixed in #7

**Comment by CorruptComputer** [comment]
Looks like this is caused by: 
```
"218_3152720314"
{
	"tags"
	{
		"0"		"NONSTEAM"
		"1"		"Sorting"
	}
	"hidden"		"1"
}
```
Which is a non-steam game added I believe.

**Comment by CorruptComputer** [comment]
Also are you sure it wasn't fixed? Checking again it runs fine for me:
```
[user@pc ProtonDB-to-Steam-Library]$ python ProtonDB-to-Steam-Library.py -s sharedconfig.vdf
Selected: sharedconfig.vdf
20900 platinum
292030 platinum
20920 bronze
388750 silver
348550 gold
242700 gold
222420 platinum
222440 gold
222940 gold
571260 silver
237110 platinum
452510 gold
215530 platinum
72850 gold
255070 gold
260130 pending
237890 borked
312790 pending
221380 platinum
226840 pending
315850 pending
239200 pending
236730 pending
91200 pending
290340 pending
1700 platinum
289200 pending
507490 silver
46410 bronze
272010 gold
204300 pending
242920 gold
107100 pending
238460 silver
460790 gold
219760 platinum
113200 gold
250900 pending
7670 gold
409710 gold
8850 gold
409720 silver
8870 pending
362890 pending
249650 platinum
586140 borked
302710 pending
281220 platinum
49520 gold
285800 pending
107300 borked
274500 pending
274190 pending
262940 pending
99810 pending
204360 gold
234080 gold
434420 gold
255710 platinum
228200 gold
4560 gold
9340 silver
20540 gold
730 gold
248390 platinum
203770 pending
247080 pending
107310 borked
211420 gold
236430 gold
335300 platinum
374320 gold
50620 borked
50650 pending
462780 gold
320320 silver
91310 pending
216250 pending
292910 pending
226620 pending
337000 bronze
214170 platinum
219780 gold
230230 platinum
435150 gold
373420 platinum
219740 pending
318130 borked
208200 gold
570 platinum
252350 bronze
47810 gold
65800 gold
249050 gold
429620 pending
39190 gold
39200 gold
39160 platinum
262280 pending
232050 borked
306130 gold
489830 silver
339580 platinum
289130 gold
265610 bronze
641990 pending
347830 borked
228260 borked
38400 gold
38410 gold
38420 gold
674520 platinum
39150 silver
245550 platinum
212680 pending
225280 platinum
214150 borked
226860 gold
4000 silver
258970 platinum
296490 gold
223220 borked
246960 borked
265930 pending
438490 borked
460870 borked
219990 platinum
316790 pending
439700 borked
70 pending
220 pending
420 pending
253230 silver
863550 gold
257850 pending
282900 gold
826600 gold
304430 platinum
7110 silver
12380 pending
12370 pending
225540 borked
1250 pending
232090 gold
368230 pending
102500 platinum
373180 platinum
391260 pending
397500 pending
550 platinum
207170 platinum
251730 gold
407230 silver
285160 platinum
214510 silver
319630 platinum
360430 bronze
42910 borked
202090 pending
284240 gold
25980 platinum
363440 silver
43110 silver
43160 pending
61700 borked
489520 gold
22100 platinum
48700 platinum
48720 platinum
389870 pending
760060 platinum
545270 gold
109600 gold
15700 gold
211360 platinum
264200 platinum
425220 bronze
331600 silver
266210 gold
12710 pending
306670 pending
115800 pending
992640 gold
238960 gold
237570 gold
329490 platinum
291650 platinum
246620 pending
400 pending
611500 silver
314410 platinum
70400 silver
55110 platinum
400660 pending
391220 platinum
217140 borked
40300 platinum
40390 borked
248820 silver
632360 gold
383980 silver
221680 silver
225640 gold
207930 platinum
9480 pending
55230 bronze
206420 pending
328760 platinum
210770 pending
263320 pending
204340 gold
41070 pending
41050 gold
41060 silver
227780 bronze
111600 bronze
41000 borked
41010 gold
201480 silver
552590 gold
418240 pending
234650 pending
346940 pending
102840 pending
326460 pending
366640 gold
381120 pending
8930 silver
289070 bronze
1313 pending
1300 pending
1309 pending
204880 platinum
461640 pending
245170 pending
365720 silver
367600 pending
207140 pending
39550 silver
39540 platinum
221910 pending
208580 gold
6060 platinum
329380 borked
322190 pending
281990 pending
463350 bronze
442780 pending
40960 bronze
16700 gold
40970 gold
40950 gold
40980 pending
535480 pending
361230 bronze
40800 pending
322500 pending
9350 gold
9420 silver
40100 gold
225840 platinum
410710 gold
429660 borked
105600 gold
4540 pending
475150 gold
203160 platinum
41500 platinum
200710 pending
298030 platinum
364360 pending
23490 gold
45760 gold
391540 pending
304930 pending
2600 gold
262150 pending
108500 platinum
255520 platinum
230190 pending
285190 pending
552500 borked
203630 platinum
240760 pending
210970 gold
445980 pending
233840 pending
7760 platinum
200510 pending
268500 bronze
223810 silver
223870 pending
433850 borked
308420 pending
WARNING: This may clear your current tags on Steam!
Would you like to save sharedconfig.vdf? (y/N)n
```

**Comment by QuakeSinatra** [comment]
yeah im sure that it still bombed out ..but that one you pointed out is the Black Mesa entry that i couldnt do anything with (which is why i tagged it hidden) so i went and zapped that entry out of the sharedconfig file fired up steam , verified the bogus entry was gone, closed steam and ran it again ... and..
.
433850 borked
308420 pending
WARNING: This may clear your current tags on Steam!
Would you like to save sharedconfig.vdf? (y/N)y
it RAN to COMPLETION !! W00t!! 
so even though the script didn't run through with the phantom entry , i was able to remove what shouldn't have been there anyway and it ran beautifully!!

Thank You ! for all your help and the awesome little proggie!

**Comment by CorruptComputer** [comment]
Interesting. It skipped past that entry for me with no problem. Would you mind if I added a partial of your sharedconfig.vdf as a test to make sure its all good from here on out?

**Comment by QuakeSinatra** [comment]
replied via email but yes its okay to use it for testing. btw using blackarch Linux
