### ISSUE TITLE
UnicodeDecodeError processing localconfig.vdf

### ISSUE THREAD

**Issue by niel** [CorruptComputer/ProtonDB-to-Steam-Library#16]
Steam found at: /home/niel/.steam/steam/userdata
Traceback (most recent call last):
  File "ProtonDB-to-Steam-Library.py", line 212, in <module>
    main(sys.argv[1:])
  File "ProtonDB-to-Steam-Library.py", line 139, in main
    sharedconfig_path = get_sharedconfig_path()
  File "ProtonDB-to-Steam-Library.py", line 75, in get_sharedconfig_path
    + vdf.load(open(os.path.join(base_path, user_id, "config/localconfig.vdf")))["UserLocalConfigStore"]["friends"]["PersonaName"])
  File "/usr/local/lib/python3.6/dist-packages/vdf/__init__.py", line 186, in load
    return parse(fp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/vdf/__init__.py", line 89, in parse
    for idx, line in enumerate(fp):
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
Unicode: 'utf-8' codec can't decode byte 0xe2 in position 6907: invalid continuation byte

The entry causing this appears to be:
```
		"103582791433507551"
		{
			"name"		"STAR WARSâ¢ Knights of the Old Republicâ¢ II: The Sith Lordsâ"
			"avatar"		"1c9e1a68198c15eb47b35c692fbfa5adeb7a6566"
		}

```
Even though this appears to be a legitimate UTF-8 decode error, the entry is created (and recreated when deleted) by Steam, preventing the file from being parsed.

**Comment by subwolf** [comment]
Would https://stackoverflow.com/questions/4299675/python-script-to-convert-from-utf-8-to-ascii fix it?

**Comment by subwolf** [comment]
Just converting to ascii is not good enough, titles in Europe or Asia will have this problem. Hmmmm.

**Comment by subwolf** [comment]
Huh, I have that in my library and did not get the error.

**Comment by CorruptComputer** [comment]
Hey @niel thanks for reporting this. I see you're on python 3.6, would you mind trying out 3.7 and see if that helps?

**Comment by CorruptComputer** [comment]
@subwolf I have this game as well, and did not have the problem. However mine doesn't have those characters in it either. May be related to steam locale, or the different version of python not being able to parse them properly.

**Comment by subwolf** [comment]
Very possible. Where do you live, @niel ?

**Comment by niel** [comment]
I'm in the UK. Not sure I can try out Python 3.7 as 3.6 is all that's in my distro's repos

**Comment by subwolf** [comment]
```subwolf@subwolf-tk:~$ python3 --version
Python 3.6.7
```

Didn't realise that. So it appears the problem is with vdf more than this library? The error is occurring so early on, at line 75. Maybe try specifying the path directly instead of letting the script decide?

**Comment by niel** [comment]
Specifying that file directly makes no difference, didn't think it would ;-)
I edited out the bad characters and ran the script successfully, lot of errors looking up entries though. That at least gets me a partially categorised list.

**Comment by CorruptComputer** [comment]
If possible could you post your sharedconfig.vdf so I can take a look?

**Comment by CorruptComputer** [comment]
So this looks like its crashing due to your Steam username having non-ascii characters in it. I can look into fixing that.

**Comment by CorruptComputer** [comment]
Could you try the version which I just uploaded and see if that fixed your issue? (90dd1a45907acb261a72580ab06b5e1b71b348fc)

**Comment by niel** [comment]
> So this looks like its crashing due to your Steam username having non-ascii characters in it. I can look into fixing that.

Not my username, one of the owned games.

Will try that version ass soon as I get time to install.

**Comment by niel** [comment]
New version is working great. Great work, many thanks.

**Comment by CorruptComputer** [comment]
@niel it was coming from localconfig.vdf which is used to lookup usernames for the Steam accounts on the device. All games are stored in sharedconfig.vdf. But I'm glad to hear it's working now!
