### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by ShayBox** [CorruptComputer/ProtonDB-to-Steam-Library#17]
I created an AUR package for this [`protondb-to-steam-library-git`](https://aur.archlinux.org/packages/protondb-to-steam-library-git/)
Some notes:
- It is `-git` because there are no tagged releases

If there are any updates to the script feel free to flag it out of date and I will update the version number, this is just for the sake of aur helpers auto updating, as this is a `-git` package it will always pull the latest version upon installing (or reinstalling)

And if there are ever tagged releases or an official version number, please let me know either here, in the aur package comments, or via a flag.

**Comment by CorruptComputer** [comment]
Ah you got there before me. I plan on starting to do releases once it stabilizes a bit for all these different configurations.

**Comment by ShayBox** [comment]
That's alright, it's still your package so you I can transfer it to you if you ever want the aur package, and once you have tagged releases you can make a non git one too :+1:

**Comment by CorruptComputer** [comment]
Going to close this for now. I don't see any problem with someone else maintaining the AUR package.
