### ISSUE TITLE
AttributeError: 'str' object has no attribute 'copy'

### ISSUE THREAD

**Issue by 3405cel** [CorruptComputer/ProtonDB-to-Steam-Library#18]
Terminal returned this error message after tagging some of my steam games:
```
Traceback (most recent call last):
  File "ProtonDB-to-Steam-Library.py", line 225, in <module>
    main(sys.argv[1:])
  File "ProtonDB-to-Steam-Library.py", line 173, in main
    tags = sharedconfig[configstore]["Software"]["Valve"]["Steam"][apps][str(app_id)]["tags"].copy()
AttributeError: 'str' object has no attribute 'copy'
```
The tags did not write to my steam library since the script threw the error.

I'm running Python 3.7.3

```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.4
DISTRIB_CODENAME=Illyria
DISTRIB_DESCRIPTION="Manjaro Linux"
```
Here is the a screenshot of my full terminal output:
[https://imgur.com/PsfwQIt](url)

**Comment by CorruptComputer** [comment]
Could you attach your sharedconfig.vdf to the issue so I can take a look?

**Comment by CorruptComputer** [comment]
Could you try the version which I just uploaded and see if that fixed your issue? (90dd1a45907acb261a72580ab06b5e1b71b348fc)

**Comment by InAUGral** [comment]
Hi CorruptComputer,
I get the same error. I have just installed Python 3 and am also running Manjaro. Running the above code did not fix my issue. I tried also specifying the full path for sharedconfig.vdf manually using -s without luck. Could this  error have anything to do with existing tag names/categories?

**Comment by saudfs** [comment]
same OS as 3405cel and with the same issue: 

`Traceback (most recent call last):
  File "ProtonDB-to-Steam-Library.py", line 241, in <module>
    main(sys.argv[1:])
  File "ProtonDB-to-Steam-Library.py", line 196, in main
    tags = sharedconfig[configstore]["Software"]["Valve"]["Steam"][apps][str(app_id)]["tags"].copy()
AttributeError: 'str' object has no attribute 'copy'`

I downloaded the latest version. The script works until it reaches a specific steam app (17080 borked) then it gives me the error.


[sharedconfig.txt](https://github.com/CorruptComputer/ProtonDB-to-Steam-Library/files/3276541/sharedconfig.txt)

**Comment by CorruptComputer** [comment]
Thanks @saudfs for including the sharedconfig, I think I may have just fixed this. This was a small goof on my part, I left one tiny check out of that update which should have fixed it. I'll get that fixed right now, and is it alright if I use a partial of your sharedconfig as a test to ensure continued compatibility?

**Comment by saudfs** [comment]
> Thanks @saudfs for including the sharedconfig, I think I may have just fixed this. This was a small goof on my part, I left one tiny check out of that update which should have fixed it. I'll get that fixed right now, and is it alright if I use a partial of your sharedconfig as a test to ensure continued compatibility?

Yes of course! I wish I could do more to help but unfortunately  I'm not a coder.

**Comment by BrosephJ** [comment]
I was just about to report this issue. Fast work @CorruptComputer !

**Comment by CorruptComputer** [comment]
Ok, I think that may be fixed then. If you test and find that it isn't please let me know and I'll re-open this!

**Comment by BrosephJ** [comment]
Script ran all the way through with no errors for me! There are around 50 games or so in my list that didn't get tagged though. Most are Linux native so that's to be expected.

**Comment by CorruptComputer** [comment]
Yeah, most native titles aren't tagged because ProtonDB doesn't return anything for them. There are a couple exceptions such as Deus Ex Mankind Divided though.

**Comment by saudfs** [comment]
Working perfectly for me! Thank you for the fix.
