### ISSUE TITLE
Request: If native linux search flag is set, add to new category in vdf

### ISSUE THREAD

**Issue by subwolf** [CorruptComputer/ProtonDB-to-Steam-Library#19]
Add an 8th column to the array, like "Linux Native", if a search comes back as native, add it to an extra category. This is only to be followed if the search native flag is used though.

**Comment by CorruptComputer** [comment]
Ok so, the reason I added the Native check was for games like Deus Ex Mankind Divided. Where it is native, but ProtonDB returns a rating for some reason still. This was to make sure Native games don't get categorized. I'm not sure if there is a need to specifically add them to a category.

**Comment by subwolf** [comment]
Understood, I understand there may still be exeptions.

**Comment by hansdampfinger666** [comment]
Apparently native is not a category you get in the JSON readout. Have you talked to the ProtonDB guys to mitigate that issue? Should be no problem for them to just add that to the data.

**Comment by hansdampfinger666** [comment]
Not sure if this is stupid, but whatever. What about using static code analysis on say steamdb (example https://steamdb.info/app/272270/) and reading the supported systems from the HTML directly if the trending flag is equal to pending.

![image](https://user-images.githubusercontent.com/34689803/59386367-c4d53b00-8d66-11e9-8a20-74c01144f542.png)

**Comment by CorruptComputer** [comment]
There's already an option to check if it's native, but because of Steam API limits you can only make 10 requests in 10 seconds. Which is why it's disabled by default now, as it adds a 1 second wait for each game.

**Comment by CorruptComputer** [comment]
I've added this feature in the newest commit.
