### ISSUE TITLE
Tool is crashing due to missing 'UserLocalConfigStore'

### ISSUE THREAD

**Issue by dreamer** [CorruptComputer/ProtonDB-to-Steam-Library#2]
File "./ProtonDB-to-Steam-Library.py", line 18, in <module>
        for appid in data["UserLocalConfigStore"]["Software"]["Valve"]["Steam"]["Apps"]:
    KeyError: 'UserLocalConfigStore'

The proper key is 'UserRoamingConfigStore'.

**Comment by CorruptComputer** [comment]
Could you attach your sharedconfig.vdf to this issue. I would like to take a look and see what's going on with it.

**Comment by CorruptComputer** [comment]
Whoops, didn't mean to close this.

**Comment by CorruptComputer** [comment]
Could you test the most recent build and see if it has fixed your issue?

**Comment by CorruptComputer** [comment]
This is confirmed to have been fixed in ad6647c
