### ISSUE TITLE
Change the Proton*,py name script in lowercase.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [CorruptComputer/ProtonDB-to-Steam-Library#23]
Here's a weird thing, as you can see, the script didn’t manage to find my file, despite having it names exactly how it was named. 
And while trying to see if it was some python dependencies issues or something, I’ve just remembered a recent issue, that i’ve had by modding Borderlands 2, the mods scripts commonly used with the game aren’t able to be load in game, if they are capitalized for some strange reason.
So, I’ve done just this, and renamed it all in lowercase.
And it worked.
![image](https://user-images.githubusercontent.com/13170204/59567261-bab78300-906b-11e9-84fe-4e21a87095fb.png)
For reference, I’m currently on the latest version of ElementaryOS Juno.

**Comment by Scotsguy** [comment]
> python3 Protondb-to-Steam-Library.py

The DB should be capitalized. Though I agree the capitalization is weird for a linux script, I usually just tab-complete (isn't that fish? it's quite good in that regard)

**Comment by PoorPocketsMcNewHold** [comment]
It is fish indeed, so that's even one more proof that i’ve didn’t mistyped it. However, Even if i’m sure using the auto-complete didn’t help either, I would like to at least take a note on fixing the readme.me then, which doesn’t capitalized DB however.

**Comment by CorruptComputer** [comment]
The README does capitalize the DB though? https://github.com/CorruptComputer/ProtonDB-to-Steam-Library#running

I'm not quite sure about how I feel about changing it for no benefit, as it may cause confusion if people who had it before re-download the files.

**Comment by PoorPocketsMcNewHold** [comment]
![Peek 16-06-2019 19-44](https://user-images.githubusercontent.com/13170204/59567529-39fa8600-906f-11e9-8254-921d04d8efd2.gif)
My bad, It's me. (No real idea where is the issue there, but at least, it's on my end).
I suppose you should then, just keep the current file name then, if really someone is starting to have the same issue as me, maybe adding a little note addressing about that, but I suppose that's optional. 
I’ll close this issue since the decision of keeping it intact has been decided.

**Comment by CorruptComputer** [comment]
Huh, I'm curious where you're reading that from with the dark mode? Also it seems your system may be unstable or somethings wrong with it flickering so much like that.

**Comment by PoorPocketsMcNewHold** [comment]
![capitalisation issue](https://user-images.githubusercontent.com/13170204/59567609-33204300-9070-11e9-911e-6a79d2ca3d37.gif)
The dark mode is just an user script. I think i’ve got a theory for that, but as i’ve said, it has literary nothing with that. I presume it's one Firefox extension i’m having, which habitually prevent from capitalizing titles which seems to also cause this DB of proton DB to be in lowercase. Pretty strange, but also embarrassing for myself to have not checked the raw readme file.
