### ISSUE TITLE
Error upon attempting to save sharedconfig.vdf

### ISSUE THREAD

**Issue by KRossKoWolf** [CorruptComputer/ProtonDB-to-Steam-Library#25]
I am able to run the script to the end, finding ratings for all of my library. However, when I reach the end and attempt to save, I keep getting the error displayed below. I've got no idea what to do next. I did follow the troubleshooting section of the readme, adding all of the games to a category - "nil". I've tried using one of, both, and also neither, the -c command & -n command to no avail. I've also attached my shared config file, in case this is of any help.

[sharedconfig.vdf.tar.gz](https://github.com/CorruptComputer/ProtonDB-to-Steam-Library/files/3321377/sharedconfig.vdf.tar.gz)

![Screenshot from 2019-06-24 02-20-57](https://user-images.githubusercontent.com/52167975/60028704-b99fda80-9697-11e9-9f26-bea03040edc1.png)

**Comment by CorruptComputer** [comment]
Huh, that is strange. Could you provide me some info:

What distro and python version are you using? 

Also do you have Steam installed through a FlatPak or Snap?

**Comment by KRossKoWolf** [comment]
Currently running on Linux Mint 19.1 Tessa. Steam was installed from the .deb available through the Linux Mint Repo and has subsequently updated to the newest available beta release, from within Steam itself. The versions of Python are 2.7.15+ & 3.6.8.

**Comment by Karpfly2822** [comment]
[sharedconfig.vdf.tar.gz](https://github.com/CorruptComputer/ProtonDB-to-Steam-Library/files/3322581/sharedconfig.vdf.tar.gz)
same error here, Linux Mint 19.1, Python 2.7.15+ and 3.6.8, Steam(latest stable) from Mint repo, non categorized games i have added to "Inne" group. I'm using Polish language.

**Comment by CorruptComputer** [comment]
Alright, I just downloaded Linux Mint and ran it in a VM. I wasn't able to reproduce this crash:
```
ngupton@MintVM:~/ProtonDB-to-Steam-Library$ pip3 install requests vdf
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.21.0)
Collecting vdf
  Downloading https://files.pythonhosted.org/packages/7a/c2/bf87cef932c45cb7b7a79a0a954e3307fcff209c7639182a2b9ae0127959/vdf-3.1-py2.py3-none-any.whl
Installing collected packages: vdf
Successfully installed vdf-3.1

ngupton@MintVM:~/ProtonDB-to-Steam-Library$ python3 ProtonDB-to-Steam-Library.py 
Steam found at: /home/ngupton/.steam/steam/userdata
Found user 0: 85729560   CorruptComputer
Only one user found.
Selected: /home/ngupton/.steam/steam/userdata/85729560/7/remote/sharedconfig.vdf
105600 gold
620 pending
[ ~cut to reduce length~ ]
638970 gold
301640 gold
WARNING: This may clear your current tags on Steam!
Would you like to save sharedconfig.vdf? (y/N)y

ngupton@MintVM:~/ProtonDB-to-Steam-Library$ python3 --version
Python 3.7.3
```

Is there any other information you could provide?

**Comment by Karpfly2822** [comment]
`python3 ProtonDB-to-Steam-Library.py`
this fixed for me, i was drag and drop script to terminal before

**Comment by CorruptComputer** [comment]
Ah, glad to hear that its working! @KRossKoWolf was this the same issue you were facing?

**Comment by KRossKoWolf** [comment]
Yeah, turns out it was. Thanks for the assist, should probably have noticed that myself.

**Comment by CorruptComputer** [comment]
After looking into this further it looks like you ran the script in python2. I added this error to the troubleshooting steps in the README: https://github.com/CorruptComputer/ProtonDB-to-Steam-Library/blob/master/README.md#troubleshooting
