### ISSUE TITLE
Rate shared games

### ISSUE THREAD

**Issue by Technetium1** [CorruptComputer/ProtonDB-to-Steam-Library#26]
Games that are shared are able to be categorized, so can there be an option to rate shared games? Currently a friend has ~300 games available in his library, but only his 4 are rated.

**Comment by CorruptComputer** [comment]
Could you send an example sharedconfig.vdf for this? The games may be stored differently in the file, so I would need to see it to be able to add this functionality.

**Comment by Scotsguy** [comment]
This works, though? Add a tag to all of them once and they'll get categorized

**Comment by CorruptComputer** [comment]
So testing this on my own machine, it does seem to work properly already. If not all your games aren't being categorized please follow the steps outlined in the README: https://github.com/CorruptComputer/ProtonDB-to-Steam-Library#troubleshooting

**Comment by Technetium1** [comment]
We had tried and it still didn't work. Decided to move to Pop_OS earlier today and it's working just fine now, but only after tagging to a random category first as per the 'troubleshooting' in the readme.
