### ISSUE TITLE
String Issue?

### ISSUE THREAD

**Issue by dmccollough1** [CorruptComputer/ProtonDB-to-Steam-Library#27]
I've tried running this a good couple dozen times now, using python and python3 at the beginning as well as with and without sudo and it always fails at the end when it asks me if I want to save it. Regardless of what I choose it won't complete. I want it to save, but when I type in y or yes, I get this:
WARNING: This may clear your current tags on Steam!
Would you like to save sharedconfig.vdf? (y/N)y
Traceback (most recent call last):
  File "ProtonDB-to-Steam-Library.py", line 220, in <module>
    main(arguments)
  File "ProtonDB-to-Steam-Library.py", line 207, in main
    check = input("Would you like to save sharedconfig.vdf? (y/N)")
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined

I'm not sure if this is a string issue or not. 
System info:
python --version == Python 2.7.15+
python3 --version == Python 3.6.8
Ubuntu 18.04.2 LTS 
Kernel 4.15.0-54-generic
bash 4.4.19
GNOME 3.28.4

**Comment by dmccollough1** [comment]
Oddly enough it refused to work. Seems to work after putting in a issue. Normal IT logic.

**Comment by CorruptComputer** [comment]
Looks like the same error as #25, were you dragging the script into the terminal to run it?

**Comment by CorruptComputer** [comment]
Actually, after looking into this further it looks like you ran the issue in python2. I added this error to the troubleshooting steps in the README: https://github.com/CorruptComputer/ProtonDB-to-Steam-Library/blob/master/README.md#troubleshooting

**Comment by dmccollough1** [comment]
It's working now, but no I didn't drag anything. I manually typed it out in
the terminal from the master folder that was in my Download directory.
