### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by XakepSDK** [CorruptComputer/ProtonDB-to-Steam-Library#3]
```
Traceback (most recent call last):
  File "protondb-tag.py", line 18, in <module>
    for appid in data["UserLocalConfigStore"]["Software"]["Valve"]["Steam"]["Apps"]:
KeyError: 'UserLocalConfigStore'
```
File script points, doesn't contain any of those strings.
But `~/.steam/steam/userdata/[userid]/config/localconfig.vdf` contains something that looks like content, that script looks for.

**Comment by CorruptComputer** [comment]
Could you send me your sharedconfig.vdf so I can take a look at it?

**Comment by XakepSDK** [comment]
https://gist.github.com/XakepSDK/3cfce2e71ad6db11e56b23e8de69585e

**Comment by CorruptComputer** [comment]
Huh. It's really strange how wildly different the format of that is from the ones I've seen. Are you on the steam beta update?

**Comment by XakepSDK** [comment]
Yes

**Comment by SleeplessSloth** [comment]
I have the same crash, here's my sharedconfig.vdf for reference

**Comment by SleeplessSloth** [comment]
I have the same crash, here's my sharedconfig.vdf for reference

[sharedconfig.vdf.zip](https://github.com/CorruptComputer/ProtonDB-to-Steam-Library/files/3266811/sharedconfig.vdf.zip)

P.S. I removed links from the "Web" section since they contained personal info

**Comment by CorruptComputer** [comment]
@SleeplessSloth and @XakepSDK I believe I have fixed this, I removed any unneeded information from the vdf files and added them to TravisCI as tests to maintain compatibility moving forward. Could you test this new version and see how it is?

**Comment by XakepSDK** [comment]
It updated only one game.
```
user@arch ~/Desktop % python protondb-tag.py 
Steam found at: /home/user/.local/share/Steam/userdata
Found user 0: [replaced]   [replaced]
Only one user found.
Selectd: /home/user/.local/share/Steam/userdata/[replaced]/7/remote/sharedconfig.vdf
428750 pending
Would you like to save sharedconfig.vdf? (y/N)y
```

**Comment by CorruptComputer** [comment]
@XakepSDK The vdf you uploaded only has one game in it. 
```
"Apps"
{
	"428750"
	{
		"cloudenabled"		"1"
	}
}
```

I believe this may be an issue related to the `UserLocalConfigStore` vs `UserRemoteConfigStore`. I am currently looking into it, but I'm not sure how far I'll get without having to contact Valve about the matter.

**Comment by XakepSDK** [comment]
I have 180 game entries in localconfig.vdf, in steam i see 172 games.
Maybe just copy them from localconfig to sharedconfig?

**Comment by CorruptComputer** [comment]
You could try that if you want, although I would be hesitant. As I do not know if that would break anything with Steam.

**Comment by CorruptComputer** [comment]
@XakepSDK Could you try the steps shown here: https://github.com/CorruptComputer/ProtonDB-to-Steam-Library#troubleshooting

A couple people have told me this resolved that issue for them.

**Comment by XakepSDK** [comment]
Looks like this is fixed. Thank you.
