### ISSUE TITLE
Lowercase making script fail.

### ISSUE THREAD

**Issue by dimension128** [CorruptComputer/ProtonDB-to-Steam-Library#9]
For some reason steam uses the string "apps" instead of "Apps" in my sharedconfig.
I suppose I could change it. But I'm reporting this anyway so maybe you can update the script to work for people who won't know how to figure this out.

>   File "./ProtonDB-to-Steam-Library.py", line 147, in main
>     for app_id in sharedconfig[configstore]["Software"]["Valve"]["Steam"]["Apps"]:
>   KeyError: 'Apps

I just did a dirty find and replace in the script for "Apps" to get it going for now.

**Comment by aTosser** [comment]
Same issue here.

**Comment by CorruptComputer** [comment]
If possible could you attach your sharedconfig.vdf? The script should have output the file's location before it crashed for you. But in case it didn't it is located here: `.../Steam/userdata/[id]/7/remote/sharedconfig.vdf`

**Comment by indykoning** [comment]
A [pull request](https://github.com/CorruptComputer/ProtonDB-to-Steam-Library/pull/7) has been created to fix this. Still it's odd of steam to have it be either upper or lower case since linux is case sensitive.

**Comment by CorruptComputer** [comment]
Fixed via #7
